/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PickupWaitingRouteImport } from './routes/pickup.waiting'
import { Route as PickupSelectRouteImport } from './routes/pickup.select'
import { Route as PickupPreviewRouteImport } from './routes/pickup.preview'
import { Route as PickupMethodRouteImport } from './routes/pickup.method'
import { Route as PickupCompleteRouteImport } from './routes/pickup.complete'
import { Route as LoginPinRouteImport } from './routes/login.pin'
import { Route as PickupFormMethodRouteImport } from './routes/pickup.form.$method'

const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupWaitingRoute = PickupWaitingRouteImport.update({
  id: '/pickup/waiting',
  path: '/pickup/waiting',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupSelectRoute = PickupSelectRouteImport.update({
  id: '/pickup/select',
  path: '/pickup/select',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupPreviewRoute = PickupPreviewRouteImport.update({
  id: '/pickup/preview',
  path: '/pickup/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupMethodRoute = PickupMethodRouteImport.update({
  id: '/pickup/method',
  path: '/pickup/method',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupCompleteRoute = PickupCompleteRouteImport.update({
  id: '/pickup/complete',
  path: '/pickup/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPinRoute = LoginPinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => LoginRoute,
} as any)
const PickupFormMethodRoute = PickupFormMethodRouteImport.update({
  id: '/pickup/form/$method',
  path: '/pickup/form/$method',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRouteWithChildren
  '/monitoring': typeof MonitoringRoute
  '/login/pin': typeof LoginPinRoute
  '/pickup/complete': typeof PickupCompleteRoute
  '/pickup/method': typeof PickupMethodRoute
  '/pickup/preview': typeof PickupPreviewRoute
  '/pickup/select': typeof PickupSelectRoute
  '/pickup/waiting': typeof PickupWaitingRoute
  '/pickup/form/$method': typeof PickupFormMethodRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRouteWithChildren
  '/monitoring': typeof MonitoringRoute
  '/login/pin': typeof LoginPinRoute
  '/pickup/complete': typeof PickupCompleteRoute
  '/pickup/method': typeof PickupMethodRoute
  '/pickup/preview': typeof PickupPreviewRoute
  '/pickup/select': typeof PickupSelectRoute
  '/pickup/waiting': typeof PickupWaitingRoute
  '/pickup/form/$method': typeof PickupFormMethodRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRouteWithChildren
  '/monitoring': typeof MonitoringRoute
  '/login/pin': typeof LoginPinRoute
  '/pickup/complete': typeof PickupCompleteRoute
  '/pickup/method': typeof PickupMethodRoute
  '/pickup/preview': typeof PickupPreviewRoute
  '/pickup/select': typeof PickupSelectRoute
  '/pickup/waiting': typeof PickupWaitingRoute
  '/pickup/form/$method': typeof PickupFormMethodRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/monitoring'
    | '/login/pin'
    | '/pickup/complete'
    | '/pickup/method'
    | '/pickup/preview'
    | '/pickup/select'
    | '/pickup/waiting'
    | '/pickup/form/$method'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/monitoring'
    | '/login/pin'
    | '/pickup/complete'
    | '/pickup/method'
    | '/pickup/preview'
    | '/pickup/select'
    | '/pickup/waiting'
    | '/pickup/form/$method'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/monitoring'
    | '/login/pin'
    | '/pickup/complete'
    | '/pickup/method'
    | '/pickup/preview'
    | '/pickup/select'
    | '/pickup/waiting'
    | '/pickup/form/$method'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRouteWithChildren
  MonitoringRoute: typeof MonitoringRoute
  PickupCompleteRoute: typeof PickupCompleteRoute
  PickupMethodRoute: typeof PickupMethodRoute
  PickupPreviewRoute: typeof PickupPreviewRoute
  PickupSelectRoute: typeof PickupSelectRoute
  PickupWaitingRoute: typeof PickupWaitingRoute
  PickupFormMethodRoute: typeof PickupFormMethodRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup/waiting': {
      id: '/pickup/waiting'
      path: '/pickup/waiting'
      fullPath: '/pickup/waiting'
      preLoaderRoute: typeof PickupWaitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup/select': {
      id: '/pickup/select'
      path: '/pickup/select'
      fullPath: '/pickup/select'
      preLoaderRoute: typeof PickupSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup/preview': {
      id: '/pickup/preview'
      path: '/pickup/preview'
      fullPath: '/pickup/preview'
      preLoaderRoute: typeof PickupPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup/method': {
      id: '/pickup/method'
      path: '/pickup/method'
      fullPath: '/pickup/method'
      preLoaderRoute: typeof PickupMethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup/complete': {
      id: '/pickup/complete'
      path: '/pickup/complete'
      fullPath: '/pickup/complete'
      preLoaderRoute: typeof PickupCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/pin': {
      id: '/login/pin'
      path: '/pin'
      fullPath: '/login/pin'
      preLoaderRoute: typeof LoginPinRouteImport
      parentRoute: typeof LoginRoute
    }
    '/pickup/form/$method': {
      id: '/pickup/form/$method'
      path: '/pickup/form/$method'
      fullPath: '/pickup/form/$method'
      preLoaderRoute: typeof PickupFormMethodRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LoginRouteChildren {
  LoginPinRoute: typeof LoginPinRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginPinRoute: LoginPinRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRouteWithChildren,
  MonitoringRoute: MonitoringRoute,
  PickupCompleteRoute: PickupCompleteRoute,
  PickupMethodRoute: PickupMethodRoute,
  PickupPreviewRoute: PickupPreviewRoute,
  PickupSelectRoute: PickupSelectRoute,
  PickupWaitingRoute: PickupWaitingRoute,
  PickupFormMethodRoute: PickupFormMethodRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
